Header header
bool small
float64 yaw
float64 pitch
float64 roll
float64 motor_left
float64 motor_right
float64 speed_actual
float64 angle_actual
float64 throttle
float64 steering
 
float64 balancing_in
float64 balancing_out
float64 balancing_set
float64 speed_in
float64 speed_out
float64 speed_set


float64 gyro_x
float64 gyro_y
float64 gyro_z

float64 acc_x
float64 acc_y
float64 acc_z

bool fallen